#!/bin/sh

if [ "$APP_ENVIRONMENT" = "production" ]; then
    php artisan octane:frankenphp --max-requests=250 --port=8000 --host=127.0.0.1
else
    php artisan octane:frankenphp --max-requests=1 --port=8000 --poll --host=127.0.0.1
fi
